version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: dockerfiles/Dockerfile-dev
    restart: always
    environment:
      PORT: ${DEV_PORT}
    ports:
      - ${DEV_PORT}:${DEV_PORT}
